# # name: Deploy Static Website to S3

# # on:
# #   push:
# #     branches:
# #       - main

# # jobs:
# #   deploy:
# #     runs-on: ubuntu-latest

# #     steps:
# #     - name: Checkout code
# #       uses: actions/checkout@v4

# #     - name: Install AWS CLI
# #       run: |
# #         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
# #         unzip awscliv2.zip
# #         sudo ./aws/install

# #     - name: Deploy to S3
# #       env:
# #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
# #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# #         AWS_REGION: ${{ secrets.AWS_REGION }}
# #         S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
# #       run: |
# #         aws s3 sync . s3://$S3_BUCKET_NAME --delete --region $AWS_REGION



# # name: Deploy to S3

# # on:
# #   push:
# #     branches: [main] 

# # jobs:
# #   deploy:
# #     runs-on: ubuntu-latest

# #     steps:
# #     - name: Checkout repo
# #       uses: actions/checkout@v4

# #     - name: Configure AWS credentials
# #       uses: aws-actions/configure-aws-credentials@v4
# #       with:
# #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
# #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# #         aws-region: ${{ secrets.AWS_REGION }}

# #     - name: Sync files to S3
# #       run: |
# #         aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --acl public-read "max-age=3600"


# name: Upload Website

# on:
#   push:
#     branches:
#     - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl public-read --follow-symlinks --delete
#       env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
#         SOURCE_DIR: 'public'      # optional: defaults to entire repository




# name: CI/CD for day86

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v1

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Deploy Static Site to S3 Bucket
#         run: aws s3 sync . s3://day86 --delete




        

name: Deploy Static Website to S3

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          # AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}           # You can hardcode if you prefer
          SOURCE_DIR: 'public'                            # Adjust if your output folder is different
